# cargo-deny config
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
]

[licenses]
allow = ["MIT", "ISC", "BSD-3-Clause", "Apache-2.0", "Unicode-3.0"]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"
